ci:
  autoupdate_schedule: "monthly"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: no-commit-to-branch
        args: [-b, master]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        exclude: ^docs/conf.py

  - repo: https://github.com/yaq-project/yaq-traits
    rev: v2023.6.0
    hooks:
      - id: yaq-traits-check
      - id: yaq-traits-compose

